AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function triggered by EventBridge schedule to fetch API data and store in DynamoDB

Parameters:
  ApiEndpointBase:
    Type: String
    Description: The base API endpoint URL to fetch data from (without the symbol)
    Default: https://api.gold-api.com/price
  
  TableName:
    Type: String
    Description: Name of the DynamoDB table
    Default: PriceDataTable
    
  LogLevel:
    Type: String
    Description: Log level for the Lambda function
    Default: INFO
    AllowedValues:
      - DEBUG
      - INFO
      - WARNING
      - ERROR
      - CRITICAL

Resources:
  DependenciesLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: dependencies-layer
        Description: Dependencies for functions
        ContentUri: ./layer/
        CompatibleRuntimes:
          - python3.10
        RetentionPolicy: Retain

  # DynamoDB Table
  ApiDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: DateIndex
          KeySchema:
            - AttributeName: date
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # Lambda Function
  ApiDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Layers:
        - !Ref DependenciesLayer
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Timeout: 60
      MemorySize: 128
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref TableName
          API_ENDPOINT_BASE: !Ref ApiEndpointBase
          LOG_LEVEL: !Ref LogLevel
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ApiDataTable
        # Allow Lambda to make outbound API calls
        - Statement:
            - Effect: Allow
              Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource: '*'

  # EventBridge Schedule Rule (Monday to Friday)
  WeekdayScheduleRule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: WeekdayApiDataSchedule
      Description: Schedule to trigger Lambda function on weekdays
      FlexibleTimeWindow:
        Mode: "OFF"
      ScheduleExpression: cron(0 22 ? * MON-FRI *)  # Runs at 12:00 PM UTC on weekdays
      Target:
        Arn: !GetAtt ApiDataFunction.Arn
        RoleArn: !GetAtt SchedulerExecutionRole.Arn

  # IAM Role for EventBridge Scheduler
  SchedulerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole

Outputs:
  ApiDataFunction:
    Description: API Data Lambda Function ARN
    Value: !GetAtt ApiDataFunction.Arn
  ApiDataTable:
    Description: DynamoDB Table Name
    Value: !Ref ApiDataTable
